# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
orbs:
  jira: circleci/jira@1.3.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  buld-and-deploy:
    parameters:
      env:
        type: string
        default: dev
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      - image: cimg/base:stable
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
      - jira/notify:
          environment_type: << parameters.env >> 
          environment: << parameters.env >>  
          job_type: deployment  
          scan_commit_body: true

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build-and-deploy-project:
    jobs:
      - buld-and-deploy: 
          env: development
          filters:
            branches:
              only:
                - master
      - buld-and-deploy: 
          env: staging
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - /^staging-v[\d]{4}[-][\d]{2}[-][\d]{2}[a-z]?$/
  


