# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
orbs:
  jira-orb: weichonglu/jira-orb@0.0.43

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  buld-and-deploy:
    parameters:
      env:
        type: string
        default: dev
      env_type:
        type: string
        default: development
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      - image: cimg/base:stable
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - jira-orb/slack_start:
          github_organization: WeiChongLu
          jira_organization: waylontest
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
      - jira-orb/slack_end:
          github_organization: WeiChongLu
          jira_organization: waylontest
      - jira-orb/jira_notify:
          environment_type: << parameters.env_type >> 
          environment: << parameters.env >>  
          job_type: deployment  
          scan_commit_body: true
          pipeline_id: "<< pipeline.id >>"
          pipeline_number: "<< pipeline.number >>"

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build-and-deploy-project:
    jobs:
      - buld-and-deploy:
          context:
            - jira_orb_context
          env: dev
          env_type: development
          filters:
            branches:
              only:
                - master
      - buld-and-deploy:
          context:
            - jira_orb_context
          env: staging
          env_type: staging
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
               - /^staging-v[\d]{4}[-][\d]{2}[-][\d]{2}[a-z]?$/
      - buld-and-deploy: 
          context:
            - jira_orb_context
          env: prod
          env_type: production
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
               - /^prod-v[\d]{4}[-][\d]{2}[-][\d]{2}[a-z]?$/
