# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

setup: true

parameters:
  environment:
    default: prod
    type: string
orbs:
  continuation: circleci/continuation@0.3.1
 # Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  PR-checking:
    jobs:
      - continuation/continue:
          configuration_path: ".circleci/main_workflow.yml" 
          parameters: /home/circleci/params.json
          pre-steps:
            - run:
                command: |
                  if [ "${CIRCLE_PULL_REQUEST##*/}" != "" ];then
                    IS_PR=true
                    echo "Is a pull request"
                  else
                    IS_PR=false
                  fi
                  echo '{ "is_pr": '$IS_PR' }' >> /home/circleci/params.json
                  echo "1234 '<< pipeline.parameters.environment >>' '$IS_PR'"